apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cao-supervisor
  namespace: cao-cluster
spec:
  template:
    spec:
      containers:
        - name: cao-node
          env:
            - name: AWS_ROLE_ARN
              value: "<irsa-role-arn>"
            - name: AWS_WEB_IDENTITY_TOKEN_FILE
              value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
          volumeMounts:
            - name: aws-iam-token
              mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
              readOnly: true
      volumes:
        - name: aws-iam-token
          projected:
            sources:
              - serviceAccountToken:
                  audience: sts.amazonaws.com
                  expirationSeconds: 86400
                  path: token
